/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 99
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 16
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_webvtt_token1 = 1,
  anon_sym_BOM = 2,
  sym__newline = 3,
  sym__blank = 4,
  sym__ws = 5,
  anon_sym_WEBVTT = 6,
  sym_title = 7,
  anon_sym_COLON = 8,
  anon_sym_EQ = 9,
  sym_metadata_name = 10,
  aux_sym_metadata_value_token1 = 11,
  sym_comment = 12,
  aux_sym_style_token1 = 13,
  sym_stylesheet = 14,
  aux_sym_region_token1 = 15,
  sym__keyword_identifier = 16,
  anon_sym_DASH_DASH_GT = 17,
  sym_timestamp = 18,
  sym_setting_name = 19,
  sym_setting_value = 20,
  anon_sym_AMP = 21,
  aux_sym_cue_text_token1 = 22,
  sym_text = 23,
  sym_entity = 24,
  anon_sym_LT = 25,
  anon_sym_DOT = 26,
  anon_sym_GT = 27,
  anon_sym_LT_SLASH = 28,
  sym_tag_name = 29,
  sym_class_name = 30,
  sym_annotation = 31,
  sym_webvtt = 32,
  sym_header = 33,
  sym_metadata = 34,
  sym_metadata_value = 35,
  sym__block = 36,
  sym_style = 37,
  sym_region = 38,
  sym_cue = 39,
  sym_cue_identifier = 40,
  sym_cue_timing = 41,
  sym__settings = 42,
  sym_setting = 43,
  sym_cue_text = 44,
  sym_start_tag = 45,
  sym_end_tag = 46,
  sym_timestamp_tag = 47,
  aux_sym_webvtt_repeat1 = 48,
  aux_sym_header_repeat1 = 49,
  aux_sym_region_repeat1 = 50,
  aux_sym_cue_repeat1 = 51,
  aux_sym__settings_repeat1 = 52,
  aux_sym_cue_text_repeat1 = 53,
  aux_sym_start_tag_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_webvtt_token1] = "webvtt_token1",
  [anon_sym_BOM] = "\ufeff",
  [sym__newline] = "_newline",
  [sym__blank] = "_blank",
  [sym__ws] = "_ws",
  [anon_sym_WEBVTT] = "WEBVTT",
  [sym_title] = "title",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [sym_metadata_name] = "metadata_name",
  [aux_sym_metadata_value_token1] = "metadata_value_token1",
  [sym_comment] = "comment",
  [aux_sym_style_token1] = "STYLE",
  [sym_stylesheet] = "stylesheet",
  [aux_sym_region_token1] = "REGION",
  [sym__keyword_identifier] = "cue_identifier",
  [anon_sym_DASH_DASH_GT] = "-->",
  [sym_timestamp] = "timestamp",
  [sym_setting_name] = "setting_name",
  [sym_setting_value] = "setting_value",
  [anon_sym_AMP] = "text",
  [aux_sym_cue_text_token1] = "text",
  [sym_text] = "text",
  [sym_entity] = "entity",
  [anon_sym_LT] = "<",
  [anon_sym_DOT] = ".",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [sym_tag_name] = "tag_name",
  [sym_class_name] = "class_name",
  [sym_annotation] = "annotation",
  [sym_webvtt] = "webvtt",
  [sym_header] = "header",
  [sym_metadata] = "metadata",
  [sym_metadata_value] = "metadata_value",
  [sym__block] = "_block",
  [sym_style] = "style",
  [sym_region] = "region",
  [sym_cue] = "cue",
  [sym_cue_identifier] = "cue_identifier",
  [sym_cue_timing] = "cue_timing",
  [sym__settings] = "_settings",
  [sym_setting] = "setting",
  [sym_cue_text] = "cue_text",
  [sym_start_tag] = "start_tag",
  [sym_end_tag] = "end_tag",
  [sym_timestamp_tag] = "timestamp_tag",
  [aux_sym_webvtt_repeat1] = "webvtt_repeat1",
  [aux_sym_header_repeat1] = "header_repeat1",
  [aux_sym_region_repeat1] = "region_repeat1",
  [aux_sym_cue_repeat1] = "cue_repeat1",
  [aux_sym__settings_repeat1] = "_settings_repeat1",
  [aux_sym_cue_text_repeat1] = "cue_text_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_webvtt_token1] = aux_sym_webvtt_token1,
  [anon_sym_BOM] = anon_sym_BOM,
  [sym__newline] = sym__newline,
  [sym__blank] = sym__blank,
  [sym__ws] = sym__ws,
  [anon_sym_WEBVTT] = anon_sym_WEBVTT,
  [sym_title] = sym_title,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_metadata_name] = sym_metadata_name,
  [aux_sym_metadata_value_token1] = aux_sym_metadata_value_token1,
  [sym_comment] = sym_comment,
  [aux_sym_style_token1] = aux_sym_style_token1,
  [sym_stylesheet] = sym_stylesheet,
  [aux_sym_region_token1] = aux_sym_region_token1,
  [sym__keyword_identifier] = sym_cue_identifier,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [sym_timestamp] = sym_timestamp,
  [sym_setting_name] = sym_setting_name,
  [sym_setting_value] = sym_setting_value,
  [anon_sym_AMP] = sym_text,
  [aux_sym_cue_text_token1] = sym_text,
  [sym_text] = sym_text,
  [sym_entity] = sym_entity,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [sym_tag_name] = sym_tag_name,
  [sym_class_name] = sym_class_name,
  [sym_annotation] = sym_annotation,
  [sym_webvtt] = sym_webvtt,
  [sym_header] = sym_header,
  [sym_metadata] = sym_metadata,
  [sym_metadata_value] = sym_metadata_value,
  [sym__block] = sym__block,
  [sym_style] = sym_style,
  [sym_region] = sym_region,
  [sym_cue] = sym_cue,
  [sym_cue_identifier] = sym_cue_identifier,
  [sym_cue_timing] = sym_cue_timing,
  [sym__settings] = sym__settings,
  [sym_setting] = sym_setting,
  [sym_cue_text] = sym_cue_text,
  [sym_start_tag] = sym_start_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_timestamp_tag] = sym_timestamp_tag,
  [aux_sym_webvtt_repeat1] = aux_sym_webvtt_repeat1,
  [aux_sym_header_repeat1] = aux_sym_header_repeat1,
  [aux_sym_region_repeat1] = aux_sym_region_repeat1,
  [aux_sym_cue_repeat1] = aux_sym_cue_repeat1,
  [aux_sym__settings_repeat1] = aux_sym__settings_repeat1,
  [aux_sym_cue_text_repeat1] = aux_sym_cue_text_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_webvtt_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BOM] = {
    .visible = true,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__blank] = {
    .visible = false,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_WEBVTT] = {
    .visible = true,
    .named = false,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_metadata_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_metadata_value_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_style_token1] = {
    .visible = true,
    .named = false,
  },
  [sym_stylesheet] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_region_token1] = {
    .visible = true,
    .named = false,
  },
  [sym__keyword_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_timestamp] = {
    .visible = true,
    .named = true,
  },
  [sym_setting_name] = {
    .visible = true,
    .named = true,
  },
  [sym_setting_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_cue_text_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_entity] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_class_name] = {
    .visible = true,
    .named = true,
  },
  [sym_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_webvtt] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata_value] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_style] = {
    .visible = true,
    .named = true,
  },
  [sym_region] = {
    .visible = true,
    .named = true,
  },
  [sym_cue] = {
    .visible = true,
    .named = true,
  },
  [sym_cue_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_cue_timing] = {
    .visible = true,
    .named = true,
  },
  [sym__settings] = {
    .visible = false,
    .named = true,
  },
  [sym_setting] = {
    .visible = true,
    .named = true,
  },
  [sym_cue_text] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_timestamp_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_webvtt_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_region_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cue_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__settings_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cue_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_annotation = 1,
  field_class = 2,
  field_end = 3,
  field_identifier = 4,
  field_name = 5,
  field_start = 6,
  field_timing = 7,
  field_title = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_annotation] = "annotation",
  [field_class] = "class",
  [field_end] = "end",
  [field_identifier] = "identifier",
  [field_name] = "name",
  [field_start] = "start",
  [field_timing] = "timing",
  [field_title] = "title",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 2},
  [10] = {.index = 15, .length = 1},
  [11] = {.index = 16, .length = 1},
  [12] = {.index = 17, .length = 2},
  [13] = {.index = 19, .length = 2},
  [14] = {.index = 21, .length = 2},
  [15] = {.index = 23, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_title, 2},
  [2] =
    {field_timing, 0},
  [3] =
    {field_name, 0},
    {field_value, 2},
  [5] =
    {field_identifier, 0},
    {field_timing, 2},
  [7] =
    {field_end, 2},
    {field_start, 0},
  [9] =
    {field_name, 0},
    {field_value, 3},
  [11] =
    {field_end, 3},
    {field_start, 0},
  [13] =
    {field_end, 4},
    {field_start, 0},
  [15] =
    {field_name, 1},
  [16] =
    {field_class, 1},
  [17] =
    {field_class, 2, .inherited = true},
    {field_name, 1},
  [19] =
    {field_class, 0, .inherited = true},
    {field_class, 1, .inherited = true},
  [21] =
    {field_annotation, 3},
    {field_name, 1},
  [23] =
    {field_annotation, 4},
    {field_class, 2, .inherited = true},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(51);
      ADVANCE_MAP(
        '\n', 52,
        '\r', 1,
        '&', 111,
        '.', 118,
        ':', 61,
        '<', 116,
        '=', 62,
        '>', 119,
        'R', 122,
        'S', 130,
        'W', 123,
        0xfeff, 53,
        '\t', 57,
        ' ', 57,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      if (lookahead != 0) ADVANCE(96);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(52);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 52,
        '\r', 1,
        '-', 11,
        '.', 118,
        '>', 119,
        'W', 24,
        0xfeff, 53,
        '\t', 57,
        ' ', 57,
      );
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(55);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(56);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(40);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(5);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(54);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(54);
      if (lookahead == '\r') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(41);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == '.') ADVANCE(37);
      END_STATE();
    case 13:
      if (lookahead == '.') ADVANCE(37);
      if (lookahead == ':') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(35);
      END_STATE();
    case 18:
      if (lookahead == ';') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      if (lookahead == ';') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 20:
      if (lookahead == ';') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == '>') ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(137);
      END_STATE();
    case 22:
      if (lookahead == '>') ADVANCE(107);
      END_STATE();
    case 23:
      if (lookahead == 'B') ADVANCE(27);
      END_STATE();
    case 24:
      if (lookahead == 'E') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'T') ADVANCE(58);
      END_STATE();
    case 26:
      if (lookahead == 'T') ADVANCE(25);
      END_STATE();
    case 27:
      if (lookahead == 'V') ADVANCE(26);
      END_STATE();
    case 28:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(108);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 39:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '&' &&
          lookahead != '.' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(136);
      END_STATE();
    case 40:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(98);
      END_STATE();
    case 41:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(102);
      END_STATE();
    case 42:
      if (eof) ADVANCE(51);
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '&') ADVANCE(112);
      if (lookahead == '<') ADVANCE(117);
      if (lookahead != 0) ADVANCE(114);
      END_STATE();
    case 43:
      if (eof) ADVANCE(51);
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == ':') ADVANCE(61);
      if (lookahead == '=') ADVANCE(62);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 44:
      if (eof) ADVANCE(51);
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == ':') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(109);
      END_STATE();
    case 45:
      if (eof) ADVANCE(51);
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == 'N') ADVANCE(81);
      if (lookahead == 'R') ADVANCE(73);
      if (lookahead == 'S') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (lookahead != 0) ADVANCE(96);
      END_STATE();
    case 46:
      if (eof) ADVANCE(51);
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(110);
      END_STATE();
    case 47:
      if (eof) ADVANCE(51);
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0) ADVANCE(96);
      END_STATE();
    case 48:
      if (eof) ADVANCE(51);
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead != 0) ADVANCE(96);
      END_STATE();
    case 49:
      if (eof) ADVANCE(51);
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 50:
      if (eof) ADVANCE(51);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '\r') ADVANCE(7);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_webvtt_token1);
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == '\r') ADVANCE(1);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_BOM);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(4);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__blank);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(4);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_WEBVTT);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_WEBVTT);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_title);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_metadata_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ':' &&
          lookahead != '=') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == '.') ADVANCE(94);
      if (lookahead == ':') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == '.') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == ':') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == ':') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == ':') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == ':') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == ';') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == ';') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == ';') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'E') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'E') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'E') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'G') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'I') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'L') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'N') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'O') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'O') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'T') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'T') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'Y') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(98);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_style_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(99);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_style_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_style_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(106);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_stylesheet);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\r') ADVANCE(10);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_region_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(103);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_region_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(103);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_region_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(106);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym__keyword_identifier);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_timestamp);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_setting_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(109);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_setting_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(110);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '#') ADVANCE(85);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '#') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym_cue_text_token1);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '&' &&
          lookahead != '<') ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_entity);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(120);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < '/' || '9' < lookahead) &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          (lookahead < 'a' || 'z' < lookahead)) ADVANCE(113);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'B') ADVANCE(133);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'E') ADVANCE(125);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'E') ADVANCE(121);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'E') ADVANCE(100);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'G') ADVANCE(126);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'I') ADVANCE(129);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'L') ADVANCE(124);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'N') ADVANCE(104);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'O') ADVANCE(128);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'T') ADVANCE(134);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'T') ADVANCE(59);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'T') ADVANCE(131);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'V') ADVANCE(132);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'Y') ADVANCE(127);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(135);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_class_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '&' &&
          lookahead != '.' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(136);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_annotation);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '>') ADVANCE(137);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 45},
  [3] = {.lex_state = 42},
  [4] = {.lex_state = 42},
  [5] = {.lex_state = 42},
  [6] = {.lex_state = 42},
  [7] = {.lex_state = 42},
  [8] = {.lex_state = 42},
  [9] = {.lex_state = 42},
  [10] = {.lex_state = 42},
  [11] = {.lex_state = 42},
  [12] = {.lex_state = 42},
  [13] = {.lex_state = 42},
  [14] = {.lex_state = 47},
  [15] = {.lex_state = 44},
  [16] = {.lex_state = 44},
  [17] = {.lex_state = 44},
  [18] = {.lex_state = 44},
  [19] = {.lex_state = 47},
  [20] = {.lex_state = 48},
  [21] = {.lex_state = 44},
  [22] = {.lex_state = 47},
  [23] = {.lex_state = 46},
  [24] = {.lex_state = 44},
  [25] = {.lex_state = 47},
  [26] = {.lex_state = 44},
  [27] = {.lex_state = 43},
  [28] = {.lex_state = 49},
  [29] = {.lex_state = 47},
  [30] = {.lex_state = 43},
  [31] = {.lex_state = 45},
  [32] = {.lex_state = 45},
  [33] = {.lex_state = 45},
  [34] = {.lex_state = 45},
  [35] = {.lex_state = 45},
  [36] = {.lex_state = 45},
  [37] = {.lex_state = 45},
  [38] = {.lex_state = 45},
  [39] = {.lex_state = 47},
  [40] = {.lex_state = 45},
  [41] = {.lex_state = 45},
  [42] = {.lex_state = 47},
  [43] = {.lex_state = 47},
  [44] = {.lex_state = 47},
  [45] = {.lex_state = 47},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 45},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 45},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 45},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 45},
  [54] = {.lex_state = 45},
  [55] = {.lex_state = 45},
  [56] = {.lex_state = 50},
  [57] = {.lex_state = 45},
  [58] = {.lex_state = 45},
  [59] = {.lex_state = 45},
  [60] = {.lex_state = 45},
  [61] = {.lex_state = 45},
  [62] = {.lex_state = 45},
  [63] = {.lex_state = 45},
  [64] = {.lex_state = 45},
  [65] = {.lex_state = 45},
  [66] = {.lex_state = 45},
  [67] = {.lex_state = 45},
  [68] = {.lex_state = 45},
  [69] = {.lex_state = 45},
  [70] = {.lex_state = 45},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 45},
  [73] = {.lex_state = 45},
  [74] = {.lex_state = 45},
  [75] = {.lex_state = 9},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 21},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 45},
  [80] = {.lex_state = 44},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 45},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 21},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 9},
  [89] = {.lex_state = 39},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 9},
  [96] = {.lex_state = 9},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_webvtt_token1] = ACTIONS(1),
    [anon_sym_BOM] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__blank] = ACTIONS(1),
    [sym__ws] = ACTIONS(1),
    [anon_sym_WEBVTT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_metadata_value_token1] = ACTIONS(1),
    [aux_sym_style_token1] = ACTIONS(1),
    [aux_sym_region_token1] = ACTIONS(1),
    [sym_timestamp] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [sym_entity] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_webvtt] = STATE(90),
    [sym_header] = STATE(58),
    [aux_sym_webvtt_token1] = ACTIONS(3),
    [anon_sym_BOM] = ACTIONS(5),
    [anon_sym_WEBVTT] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(11), 1,
      aux_sym_metadata_value_token1,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      aux_sym_style_token1,
    ACTIONS(17), 1,
      aux_sym_region_token1,
    ACTIONS(19), 1,
      sym__keyword_identifier,
    ACTIONS(21), 1,
      sym_timestamp,
    STATE(32), 1,
      sym_cue_timing,
    STATE(88), 1,
      sym_cue_identifier,
    ACTIONS(9), 2,
      ts_builtin_sym_end,
      sym__blank,
    STATE(74), 4,
      sym__block,
      sym_style,
      sym_region,
      sym_cue,
  [35] = 8,
    ACTIONS(25), 1,
      sym__newline,
    ACTIONS(27), 1,
      anon_sym_AMP,
    ACTIONS(31), 1,
      anon_sym_LT,
    ACTIONS(33), 1,
      anon_sym_LT_SLASH,
    STATE(54), 1,
      sym_cue_text,
    ACTIONS(23), 2,
      ts_builtin_sym_end,
      sym__blank,
    ACTIONS(29), 3,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
    STATE(4), 4,
      sym_start_tag,
      sym_end_tag,
      sym_timestamp_tag,
      aux_sym_cue_text_repeat1,
  [66] = 7,
    ACTIONS(31), 1,
      anon_sym_LT,
    ACTIONS(33), 1,
      anon_sym_LT_SLASH,
    ACTIONS(37), 1,
      sym__newline,
    ACTIONS(39), 1,
      anon_sym_AMP,
    ACTIONS(35), 2,
      ts_builtin_sym_end,
      sym__blank,
    ACTIONS(41), 3,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
    STATE(5), 4,
      sym_start_tag,
      sym_end_tag,
      sym_timestamp_tag,
      aux_sym_cue_text_repeat1,
  [94] = 7,
    ACTIONS(45), 1,
      sym__newline,
    ACTIONS(47), 1,
      anon_sym_AMP,
    ACTIONS(53), 1,
      anon_sym_LT,
    ACTIONS(56), 1,
      anon_sym_LT_SLASH,
    ACTIONS(43), 2,
      ts_builtin_sym_end,
      sym__blank,
    ACTIONS(50), 3,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
    STATE(5), 4,
      sym_start_tag,
      sym_end_tag,
      sym_timestamp_tag,
      aux_sym_cue_text_repeat1,
  [122] = 2,
    ACTIONS(61), 3,
      sym__newline,
      anon_sym_AMP,
      anon_sym_LT,
    ACTIONS(59), 6,
      ts_builtin_sym_end,
      sym__blank,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
      anon_sym_LT_SLASH,
  [136] = 2,
    ACTIONS(65), 3,
      sym__newline,
      anon_sym_AMP,
      anon_sym_LT,
    ACTIONS(63), 6,
      ts_builtin_sym_end,
      sym__blank,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
      anon_sym_LT_SLASH,
  [150] = 2,
    ACTIONS(69), 3,
      sym__newline,
      anon_sym_AMP,
      anon_sym_LT,
    ACTIONS(67), 6,
      ts_builtin_sym_end,
      sym__blank,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
      anon_sym_LT_SLASH,
  [164] = 2,
    ACTIONS(73), 3,
      sym__newline,
      anon_sym_AMP,
      anon_sym_LT,
    ACTIONS(71), 6,
      ts_builtin_sym_end,
      sym__blank,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
      anon_sym_LT_SLASH,
  [178] = 2,
    ACTIONS(77), 3,
      sym__newline,
      anon_sym_AMP,
      anon_sym_LT,
    ACTIONS(75), 6,
      ts_builtin_sym_end,
      sym__blank,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
      anon_sym_LT_SLASH,
  [192] = 2,
    ACTIONS(81), 3,
      sym__newline,
      anon_sym_AMP,
      anon_sym_LT,
    ACTIONS(79), 6,
      ts_builtin_sym_end,
      sym__blank,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
      anon_sym_LT_SLASH,
  [206] = 2,
    ACTIONS(85), 3,
      sym__newline,
      anon_sym_AMP,
      anon_sym_LT,
    ACTIONS(83), 6,
      ts_builtin_sym_end,
      sym__blank,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
      anon_sym_LT_SLASH,
  [220] = 2,
    ACTIONS(89), 3,
      sym__newline,
      anon_sym_AMP,
      anon_sym_LT,
    ACTIONS(87), 6,
      ts_builtin_sym_end,
      sym__blank,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
      anon_sym_LT_SLASH,
  [234] = 5,
    ACTIONS(93), 1,
      sym__newline,
    ACTIONS(95), 1,
      sym__ws,
    ACTIONS(97), 1,
      aux_sym_metadata_value_token1,
    STATE(60), 1,
      sym_metadata_value,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      sym__blank,
  [251] = 5,
    ACTIONS(101), 1,
      sym__newline,
    ACTIONS(103), 1,
      sym_setting_name,
    STATE(22), 1,
      sym_setting,
    STATE(63), 1,
      sym__settings,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      sym__blank,
  [268] = 5,
    ACTIONS(103), 1,
      sym_setting_name,
    ACTIONS(107), 1,
      sym__newline,
    STATE(22), 1,
      sym_setting,
    STATE(64), 1,
      sym__settings,
    ACTIONS(105), 2,
      ts_builtin_sym_end,
      sym__blank,
  [285] = 5,
    ACTIONS(103), 1,
      sym_setting_name,
    ACTIONS(111), 1,
      sym__newline,
    STATE(22), 1,
      sym_setting,
    STATE(68), 1,
      sym__settings,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      sym__blank,
  [302] = 5,
    ACTIONS(103), 1,
      sym_setting_name,
    ACTIONS(115), 1,
      sym__newline,
    STATE(22), 1,
      sym_setting,
    STATE(72), 1,
      sym__settings,
    ACTIONS(113), 2,
      ts_builtin_sym_end,
      sym__blank,
  [319] = 4,
    ACTIONS(119), 1,
      sym__newline,
    ACTIONS(121), 1,
      sym__ws,
    STATE(47), 1,
      aux_sym_header_repeat1,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      sym__blank,
  [333] = 4,
    ACTIONS(125), 1,
      sym__newline,
    ACTIONS(127), 1,
      aux_sym_metadata_value_token1,
    STATE(55), 1,
      sym_metadata_value,
    ACTIONS(123), 2,
      ts_builtin_sym_end,
      sym__blank,
  [347] = 3,
    ACTIONS(131), 1,
      sym__newline,
    ACTIONS(133), 1,
      anon_sym_COLON,
    ACTIONS(129), 3,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
  [359] = 4,
    ACTIONS(137), 1,
      sym__newline,
    ACTIONS(139), 1,
      sym__ws,
    STATE(25), 1,
      aux_sym__settings_repeat1,
    ACTIONS(135), 2,
      ts_builtin_sym_end,
      sym__blank,
  [373] = 3,
    ACTIONS(143), 1,
      sym__newline,
    ACTIONS(145), 1,
      sym_setting_value,
    ACTIONS(141), 3,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
  [385] = 4,
    ACTIONS(103), 1,
      sym_setting_name,
    ACTIONS(149), 1,
      sym__newline,
    STATE(42), 1,
      sym_setting,
    ACTIONS(147), 2,
      ts_builtin_sym_end,
      sym__blank,
  [399] = 4,
    ACTIONS(149), 1,
      sym__newline,
    ACTIONS(151), 1,
      sym__ws,
    STATE(29), 1,
      aux_sym__settings_repeat1,
    ACTIONS(147), 2,
      ts_builtin_sym_end,
      sym__blank,
  [413] = 4,
    ACTIONS(103), 1,
      sym_setting_name,
    ACTIONS(155), 1,
      sym__newline,
    STATE(42), 1,
      sym_setting,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      sym__blank,
  [427] = 4,
    ACTIONS(159), 1,
      sym__newline,
    ACTIONS(161), 1,
      sym_metadata_name,
    STATE(73), 1,
      sym_metadata,
    ACTIONS(157), 2,
      ts_builtin_sym_end,
      sym__blank,
  [441] = 4,
    ACTIONS(119), 1,
      sym__newline,
    ACTIONS(165), 1,
      sym_title,
    STATE(31), 1,
      aux_sym_header_repeat1,
    ACTIONS(163), 2,
      ts_builtin_sym_end,
      sym__blank,
  [455] = 4,
    ACTIONS(169), 1,
      sym__newline,
    ACTIONS(171), 1,
      sym__ws,
    STATE(29), 1,
      aux_sym__settings_repeat1,
    ACTIONS(167), 2,
      ts_builtin_sym_end,
      sym__blank,
  [469] = 3,
    ACTIONS(176), 1,
      sym__newline,
    ACTIONS(174), 2,
      ts_builtin_sym_end,
      sym__blank,
    ACTIONS(178), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [481] = 3,
    ACTIONS(119), 1,
      sym__newline,
    STATE(49), 1,
      aux_sym_header_repeat1,
    ACTIONS(180), 2,
      ts_builtin_sym_end,
      sym__blank,
  [492] = 3,
    ACTIONS(184), 1,
      sym__newline,
    STATE(33), 1,
      aux_sym_cue_repeat1,
    ACTIONS(182), 2,
      ts_builtin_sym_end,
      sym__blank,
  [503] = 3,
    ACTIONS(184), 1,
      sym__newline,
    STATE(40), 1,
      aux_sym_cue_repeat1,
    ACTIONS(186), 2,
      ts_builtin_sym_end,
      sym__blank,
  [514] = 3,
    ACTIONS(190), 1,
      sym__newline,
    STATE(35), 1,
      aux_sym_region_repeat1,
    ACTIONS(188), 2,
      ts_builtin_sym_end,
      sym__blank,
  [525] = 3,
    ACTIONS(190), 1,
      sym__newline,
    STATE(37), 1,
      aux_sym_region_repeat1,
    ACTIONS(192), 2,
      ts_builtin_sym_end,
      sym__blank,
  [536] = 3,
    ACTIONS(119), 1,
      sym__newline,
    STATE(49), 1,
      aux_sym_header_repeat1,
    ACTIONS(194), 2,
      ts_builtin_sym_end,
      sym__blank,
  [547] = 3,
    ACTIONS(198), 1,
      sym__newline,
    STATE(37), 1,
      aux_sym_region_repeat1,
    ACTIONS(196), 2,
      ts_builtin_sym_end,
      sym__blank,
  [558] = 3,
    ACTIONS(184), 1,
      sym__newline,
    STATE(41), 1,
      aux_sym_cue_repeat1,
    ACTIONS(201), 2,
      ts_builtin_sym_end,
      sym__blank,
  [569] = 3,
    ACTIONS(205), 1,
      sym__newline,
    ACTIONS(207), 1,
      sym__ws,
    ACTIONS(203), 2,
      ts_builtin_sym_end,
      sym__blank,
  [580] = 3,
    ACTIONS(211), 1,
      sym__newline,
    STATE(40), 1,
      aux_sym_cue_repeat1,
    ACTIONS(209), 2,
      ts_builtin_sym_end,
      sym__blank,
  [591] = 3,
    ACTIONS(184), 1,
      sym__newline,
    STATE(40), 1,
      aux_sym_cue_repeat1,
    ACTIONS(214), 2,
      ts_builtin_sym_end,
      sym__blank,
  [602] = 2,
    ACTIONS(169), 1,
      sym__newline,
    ACTIONS(167), 3,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
  [611] = 3,
    ACTIONS(218), 1,
      sym__newline,
    ACTIONS(220), 1,
      sym__ws,
    ACTIONS(216), 2,
      ts_builtin_sym_end,
      sym__blank,
  [622] = 2,
    ACTIONS(224), 1,
      sym__newline,
    ACTIONS(222), 3,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
  [631] = 3,
    ACTIONS(228), 1,
      sym__newline,
    ACTIONS(230), 1,
      sym__ws,
    ACTIONS(226), 2,
      ts_builtin_sym_end,
      sym__blank,
  [642] = 4,
    ACTIONS(232), 1,
      sym__ws,
    ACTIONS(234), 1,
      anon_sym_DOT,
    ACTIONS(236), 1,
      anon_sym_GT,
    STATE(48), 1,
      aux_sym_start_tag_repeat1,
  [655] = 3,
    ACTIONS(119), 1,
      sym__newline,
    STATE(49), 1,
      aux_sym_header_repeat1,
    ACTIONS(163), 2,
      ts_builtin_sym_end,
      sym__blank,
  [666] = 4,
    ACTIONS(234), 1,
      anon_sym_DOT,
    ACTIONS(238), 1,
      sym__ws,
    ACTIONS(240), 1,
      anon_sym_GT,
    STATE(50), 1,
      aux_sym_start_tag_repeat1,
  [679] = 3,
    ACTIONS(244), 1,
      sym__newline,
    STATE(49), 1,
      aux_sym_header_repeat1,
    ACTIONS(242), 2,
      ts_builtin_sym_end,
      sym__blank,
  [690] = 3,
    ACTIONS(249), 1,
      anon_sym_DOT,
    STATE(50), 1,
      aux_sym_start_tag_repeat1,
    ACTIONS(247), 2,
      sym__ws,
      anon_sym_GT,
  [701] = 3,
    ACTIONS(119), 1,
      sym__newline,
    STATE(36), 1,
      aux_sym_header_repeat1,
    ACTIONS(252), 2,
      ts_builtin_sym_end,
      sym__blank,
  [712] = 1,
    ACTIONS(254), 3,
      sym__ws,
      anon_sym_DOT,
      anon_sym_GT,
  [718] = 2,
    ACTIONS(258), 1,
      sym__newline,
    ACTIONS(256), 2,
      ts_builtin_sym_end,
      sym__blank,
  [726] = 2,
    ACTIONS(260), 1,
      sym__newline,
    ACTIONS(209), 2,
      ts_builtin_sym_end,
      sym__blank,
  [734] = 2,
    ACTIONS(264), 1,
      sym__newline,
    ACTIONS(262), 2,
      ts_builtin_sym_end,
      sym__blank,
  [742] = 2,
    ACTIONS(268), 1,
      sym_stylesheet,
    ACTIONS(266), 2,
      ts_builtin_sym_end,
      sym__blank,
  [750] = 3,
    ACTIONS(270), 1,
      ts_builtin_sym_end,
    ACTIONS(272), 1,
      sym__blank,
    STATE(69), 1,
      aux_sym_webvtt_repeat1,
  [760] = 3,
    ACTIONS(272), 1,
      sym__blank,
    ACTIONS(274), 1,
      ts_builtin_sym_end,
    STATE(66), 1,
      aux_sym_webvtt_repeat1,
  [770] = 2,
    ACTIONS(278), 1,
      sym__newline,
    ACTIONS(276), 2,
      ts_builtin_sym_end,
      sym__blank,
  [778] = 2,
    ACTIONS(282), 1,
      sym__newline,
    ACTIONS(280), 2,
      ts_builtin_sym_end,
      sym__blank,
  [786] = 2,
    ACTIONS(286), 1,
      sym__newline,
    ACTIONS(284), 2,
      ts_builtin_sym_end,
      sym__blank,
  [794] = 2,
    ACTIONS(290), 1,
      sym__newline,
    ACTIONS(288), 2,
      ts_builtin_sym_end,
      sym__blank,
  [802] = 2,
    ACTIONS(294), 1,
      sym__newline,
    ACTIONS(292), 2,
      ts_builtin_sym_end,
      sym__blank,
  [810] = 2,
    ACTIONS(296), 1,
      sym__newline,
    ACTIONS(196), 2,
      ts_builtin_sym_end,
      sym__blank,
  [818] = 3,
    ACTIONS(298), 1,
      ts_builtin_sym_end,
    ACTIONS(300), 1,
      sym__blank,
    STATE(65), 1,
      aux_sym_webvtt_repeat1,
  [828] = 3,
    ACTIONS(270), 1,
      ts_builtin_sym_end,
    ACTIONS(272), 1,
      sym__blank,
    STATE(65), 1,
      aux_sym_webvtt_repeat1,
  [838] = 3,
    ACTIONS(272), 1,
      sym__blank,
    ACTIONS(303), 1,
      ts_builtin_sym_end,
    STATE(70), 1,
      aux_sym_webvtt_repeat1,
  [848] = 2,
    ACTIONS(307), 1,
      sym__newline,
    ACTIONS(305), 2,
      ts_builtin_sym_end,
      sym__blank,
  [856] = 3,
    ACTIONS(272), 1,
      sym__blank,
    ACTIONS(303), 1,
      ts_builtin_sym_end,
    STATE(65), 1,
      aux_sym_webvtt_repeat1,
  [866] = 3,
    ACTIONS(272), 1,
      sym__blank,
    ACTIONS(309), 1,
      ts_builtin_sym_end,
    STATE(65), 1,
      aux_sym_webvtt_repeat1,
  [876] = 3,
    ACTIONS(7), 1,
      anon_sym_WEBVTT,
    ACTIONS(311), 1,
      anon_sym_BOM,
    STATE(57), 1,
      sym_header,
  [886] = 2,
    ACTIONS(315), 1,
      sym__newline,
    ACTIONS(313), 2,
      ts_builtin_sym_end,
      sym__blank,
  [894] = 2,
    ACTIONS(317), 1,
      sym__newline,
    ACTIONS(242), 2,
      ts_builtin_sym_end,
      sym__blank,
  [902] = 1,
    ACTIONS(298), 2,
      ts_builtin_sym_end,
      sym__blank,
  [907] = 2,
    ACTIONS(319), 1,
      sym_timestamp,
    ACTIONS(321), 1,
      sym_tag_name,
  [914] = 2,
    ACTIONS(7), 1,
      anon_sym_WEBVTT,
    STATE(57), 1,
      sym_header,
  [921] = 2,
    ACTIONS(323), 1,
      anon_sym_GT,
    ACTIONS(325), 1,
      sym_annotation,
  [928] = 2,
    ACTIONS(21), 1,
      sym_timestamp,
    STATE(38), 1,
      sym_cue_timing,
  [935] = 1,
    ACTIONS(327), 2,
      ts_builtin_sym_end,
      sym__blank,
  [940] = 2,
    ACTIONS(103), 1,
      sym_setting_name,
    STATE(42), 1,
      sym_setting,
  [947] = 2,
    ACTIONS(329), 1,
      sym__ws,
    ACTIONS(331), 1,
      sym_timestamp,
  [954] = 1,
    ACTIONS(333), 2,
      ts_builtin_sym_end,
      sym__blank,
  [959] = 2,
    ACTIONS(335), 1,
      sym__ws,
    ACTIONS(337), 1,
      anon_sym_DASH_DASH_GT,
  [966] = 2,
    ACTIONS(339), 1,
      sym__ws,
    ACTIONS(341), 1,
      sym_timestamp,
  [973] = 2,
    ACTIONS(343), 1,
      anon_sym_GT,
    ACTIONS(345), 1,
      sym_annotation,
  [980] = 2,
    ACTIONS(7), 1,
      anon_sym_WEBVTT,
    STATE(67), 1,
      sym_header,
  [987] = 1,
    ACTIONS(347), 1,
      sym_timestamp,
  [991] = 1,
    ACTIONS(349), 1,
      sym__newline,
  [995] = 1,
    ACTIONS(351), 1,
      sym_class_name,
  [999] = 1,
    ACTIONS(353), 1,
      ts_builtin_sym_end,
  [1003] = 1,
    ACTIONS(355), 1,
      anon_sym_DASH_DASH_GT,
  [1007] = 1,
    ACTIONS(357), 1,
      anon_sym_GT,
  [1011] = 1,
    ACTIONS(359), 1,
      anon_sym_GT,
  [1015] = 1,
    ACTIONS(361), 1,
      anon_sym_GT,
  [1019] = 1,
    ACTIONS(363), 1,
      sym__newline,
  [1023] = 1,
    ACTIONS(365), 1,
      sym_tag_name,
  [1027] = 1,
    ACTIONS(341), 1,
      sym_timestamp,
  [1031] = 1,
    ACTIONS(367), 1,
      anon_sym_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 94,
  [SMALL_STATE(6)] = 122,
  [SMALL_STATE(7)] = 136,
  [SMALL_STATE(8)] = 150,
  [SMALL_STATE(9)] = 164,
  [SMALL_STATE(10)] = 178,
  [SMALL_STATE(11)] = 192,
  [SMALL_STATE(12)] = 206,
  [SMALL_STATE(13)] = 220,
  [SMALL_STATE(14)] = 234,
  [SMALL_STATE(15)] = 251,
  [SMALL_STATE(16)] = 268,
  [SMALL_STATE(17)] = 285,
  [SMALL_STATE(18)] = 302,
  [SMALL_STATE(19)] = 319,
  [SMALL_STATE(20)] = 333,
  [SMALL_STATE(21)] = 347,
  [SMALL_STATE(22)] = 359,
  [SMALL_STATE(23)] = 373,
  [SMALL_STATE(24)] = 385,
  [SMALL_STATE(25)] = 399,
  [SMALL_STATE(26)] = 413,
  [SMALL_STATE(27)] = 427,
  [SMALL_STATE(28)] = 441,
  [SMALL_STATE(29)] = 455,
  [SMALL_STATE(30)] = 469,
  [SMALL_STATE(31)] = 481,
  [SMALL_STATE(32)] = 492,
  [SMALL_STATE(33)] = 503,
  [SMALL_STATE(34)] = 514,
  [SMALL_STATE(35)] = 525,
  [SMALL_STATE(36)] = 536,
  [SMALL_STATE(37)] = 547,
  [SMALL_STATE(38)] = 558,
  [SMALL_STATE(39)] = 569,
  [SMALL_STATE(40)] = 580,
  [SMALL_STATE(41)] = 591,
  [SMALL_STATE(42)] = 602,
  [SMALL_STATE(43)] = 611,
  [SMALL_STATE(44)] = 622,
  [SMALL_STATE(45)] = 631,
  [SMALL_STATE(46)] = 642,
  [SMALL_STATE(47)] = 655,
  [SMALL_STATE(48)] = 666,
  [SMALL_STATE(49)] = 679,
  [SMALL_STATE(50)] = 690,
  [SMALL_STATE(51)] = 701,
  [SMALL_STATE(52)] = 712,
  [SMALL_STATE(53)] = 718,
  [SMALL_STATE(54)] = 726,
  [SMALL_STATE(55)] = 734,
  [SMALL_STATE(56)] = 742,
  [SMALL_STATE(57)] = 750,
  [SMALL_STATE(58)] = 760,
  [SMALL_STATE(59)] = 770,
  [SMALL_STATE(60)] = 778,
  [SMALL_STATE(61)] = 786,
  [SMALL_STATE(62)] = 794,
  [SMALL_STATE(63)] = 802,
  [SMALL_STATE(64)] = 810,
  [SMALL_STATE(65)] = 818,
  [SMALL_STATE(66)] = 828,
  [SMALL_STATE(67)] = 838,
  [SMALL_STATE(68)] = 848,
  [SMALL_STATE(69)] = 856,
  [SMALL_STATE(70)] = 866,
  [SMALL_STATE(71)] = 876,
  [SMALL_STATE(72)] = 886,
  [SMALL_STATE(73)] = 894,
  [SMALL_STATE(74)] = 902,
  [SMALL_STATE(75)] = 907,
  [SMALL_STATE(76)] = 914,
  [SMALL_STATE(77)] = 921,
  [SMALL_STATE(78)] = 928,
  [SMALL_STATE(79)] = 935,
  [SMALL_STATE(80)] = 940,
  [SMALL_STATE(81)] = 947,
  [SMALL_STATE(82)] = 954,
  [SMALL_STATE(83)] = 959,
  [SMALL_STATE(84)] = 966,
  [SMALL_STATE(85)] = 973,
  [SMALL_STATE(86)] = 980,
  [SMALL_STATE(87)] = 987,
  [SMALL_STATE(88)] = 991,
  [SMALL_STATE(89)] = 995,
  [SMALL_STATE(90)] = 999,
  [SMALL_STATE(91)] = 1003,
  [SMALL_STATE(92)] = 1007,
  [SMALL_STATE(93)] = 1011,
  [SMALL_STATE(94)] = 1015,
  [SMALL_STATE(95)] = 1019,
  [SMALL_STATE(96)] = 1023,
  [SMALL_STATE(97)] = 1027,
  [SMALL_STATE(98)] = 1031,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_webvtt_repeat1, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_cue_repeat1, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cue_repeat1, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_text, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_text, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_cue_text_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cue_text_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cue_text_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cue_text_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cue_text_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cue_text_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 10),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 10),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_timestamp_tag, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_timestamp_tag, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 10),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 10),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 12),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 12),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 5, 0, 12),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 5, 0, 12),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 10),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 10),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 5, 0, 14),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 5, 0, 14),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 6, 0, 15),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 6, 0, 15),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 2, 0, 1),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata, 2, 0, 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 4, 0, 6),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 4, 0, 6),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_region_repeat1, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_region_repeat1, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 5, 0, 8),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 5, 0, 8),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 6, 0, 9),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 6, 0, 9),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 3, 0, 1),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata, 3, 0, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 1, 0, 1),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_setting, 1, 0, 1),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__settings, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__settings, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 2, 0, 1),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_setting, 2, 0, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__settings, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__settings, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__settings, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__settings, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_repeat1, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__settings_repeat1, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__settings_repeat1, 2, 0, 0),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__settings_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 1, 0, 1),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata, 1, 0, 1),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue, 1, 0, 3),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue, 2, 0, 3),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region, 1, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 4, 0, 2),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_region_repeat1, 2, 0, 0),
  [198] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_region_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue, 3, 0, 5),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 3, 0, 6),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 3, 0, 6),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_cue_repeat1, 2, 0, 0),
  [211] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cue_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue, 4, 0, 5),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 4, 0, 8),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 4, 0, 8),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 3, 0, 4),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_setting, 3, 0, 4),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 5, 0, 9),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 5, 0, 9),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0),
  [244] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 13),
  [249] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 13), SHIFT_REPEAT(89),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 2),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 11),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block, 1, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cue_repeat1, 2, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 4, 0, 7),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata, 4, 0, 7),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style, 2, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_webvtt, 2, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_webvtt, 1, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata_value, 1, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata_value, 1, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 3, 0, 4),
  [282] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata, 3, 0, 4),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style, 3, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style, 1, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 5, 0, 6),
  [294] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 5, 0, 6),
  [296] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_region_repeat1, 2, 0, 0),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_webvtt_repeat1, 2, 0, 0),
  [300] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_webvtt_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_webvtt, 3, 0, 0),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 6, 0, 8),
  [307] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 6, 0, 8),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_webvtt, 4, 0, 0),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 7, 0, 9),
  [315] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 7, 0, 9),
  [317] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [327] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block, 2, 0, 0),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style, 4, 0, 0),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [353] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_identifier, 1, 0, 0),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_webvtt(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "webvtt",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
