/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 104
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 16
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_webvtt_token1 = 1,
  anon_sym_BOM = 2,
  sym__newline = 3,
  sym__blank = 4,
  sym__ws = 5,
  anon_sym_WEBVTT = 6,
  sym_title = 7,
  anon_sym_COLON = 8,
  anon_sym_EQ = 9,
  sym_metadata_name = 10,
  aux_sym_metadata_value_token1 = 11,
  sym_comment = 12,
  aux_sym_style_token1 = 13,
  sym_stylesheet = 14,
  aux_sym_region_token1 = 15,
  sym__keyword_identifier = 16,
  anon_sym_DASH_DASH_GT = 17,
  sym_timestamp = 18,
  sym_setting_name = 19,
  anon_sym_COMMA = 20,
  sym_setting_part = 21,
  anon_sym_AMP = 22,
  aux_sym_cue_text_token1 = 23,
  sym_text = 24,
  sym_entity = 25,
  anon_sym_LT = 26,
  anon_sym_DOT = 27,
  anon_sym_GT = 28,
  anon_sym_LT_SLASH = 29,
  sym_tag_name = 30,
  sym_class_name = 31,
  sym_annotation = 32,
  sym_webvtt = 33,
  sym_header = 34,
  sym_metadata = 35,
  sym_metadata_value = 36,
  sym__block = 37,
  sym_style = 38,
  sym_region = 39,
  sym_cue = 40,
  sym_cue_identifier = 41,
  sym_cue_timing = 42,
  sym__settings = 43,
  sym_setting = 44,
  sym_setting_value = 45,
  sym_cue_text = 46,
  sym_start_tag = 47,
  sym_end_tag = 48,
  sym_timestamp_tag = 49,
  aux_sym_webvtt_repeat1 = 50,
  aux_sym_header_repeat1 = 51,
  aux_sym_region_repeat1 = 52,
  aux_sym_cue_repeat1 = 53,
  aux_sym__settings_repeat1 = 54,
  aux_sym_setting_value_repeat1 = 55,
  aux_sym_cue_text_repeat1 = 56,
  aux_sym_start_tag_repeat1 = 57,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_webvtt_token1] = "webvtt_token1",
  [anon_sym_BOM] = "\ufeff",
  [sym__newline] = "_newline",
  [sym__blank] = "_blank",
  [sym__ws] = "_ws",
  [anon_sym_WEBVTT] = "WEBVTT",
  [sym_title] = "title",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [sym_metadata_name] = "metadata_name",
  [aux_sym_metadata_value_token1] = "metadata_value_token1",
  [sym_comment] = "comment",
  [aux_sym_style_token1] = "STYLE",
  [sym_stylesheet] = "stylesheet",
  [aux_sym_region_token1] = "REGION",
  [sym__keyword_identifier] = "cue_identifier",
  [anon_sym_DASH_DASH_GT] = "-->",
  [sym_timestamp] = "timestamp",
  [sym_setting_name] = "setting_name",
  [anon_sym_COMMA] = ",",
  [sym_setting_part] = "setting_part",
  [anon_sym_AMP] = "text",
  [aux_sym_cue_text_token1] = "text",
  [sym_text] = "text",
  [sym_entity] = "entity",
  [anon_sym_LT] = "<",
  [anon_sym_DOT] = ".",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [sym_tag_name] = "tag_name",
  [sym_class_name] = "class_name",
  [sym_annotation] = "annotation",
  [sym_webvtt] = "webvtt",
  [sym_header] = "header",
  [sym_metadata] = "metadata",
  [sym_metadata_value] = "metadata_value",
  [sym__block] = "_block",
  [sym_style] = "style",
  [sym_region] = "region",
  [sym_cue] = "cue",
  [sym_cue_identifier] = "cue_identifier",
  [sym_cue_timing] = "cue_timing",
  [sym__settings] = "_settings",
  [sym_setting] = "setting",
  [sym_setting_value] = "setting_value",
  [sym_cue_text] = "cue_text",
  [sym_start_tag] = "start_tag",
  [sym_end_tag] = "end_tag",
  [sym_timestamp_tag] = "timestamp_tag",
  [aux_sym_webvtt_repeat1] = "webvtt_repeat1",
  [aux_sym_header_repeat1] = "header_repeat1",
  [aux_sym_region_repeat1] = "region_repeat1",
  [aux_sym_cue_repeat1] = "cue_repeat1",
  [aux_sym__settings_repeat1] = "_settings_repeat1",
  [aux_sym_setting_value_repeat1] = "setting_value_repeat1",
  [aux_sym_cue_text_repeat1] = "cue_text_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_webvtt_token1] = aux_sym_webvtt_token1,
  [anon_sym_BOM] = anon_sym_BOM,
  [sym__newline] = sym__newline,
  [sym__blank] = sym__blank,
  [sym__ws] = sym__ws,
  [anon_sym_WEBVTT] = anon_sym_WEBVTT,
  [sym_title] = sym_title,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_metadata_name] = sym_metadata_name,
  [aux_sym_metadata_value_token1] = aux_sym_metadata_value_token1,
  [sym_comment] = sym_comment,
  [aux_sym_style_token1] = aux_sym_style_token1,
  [sym_stylesheet] = sym_stylesheet,
  [aux_sym_region_token1] = aux_sym_region_token1,
  [sym__keyword_identifier] = sym_cue_identifier,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [sym_timestamp] = sym_timestamp,
  [sym_setting_name] = sym_setting_name,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_setting_part] = sym_setting_part,
  [anon_sym_AMP] = sym_text,
  [aux_sym_cue_text_token1] = sym_text,
  [sym_text] = sym_text,
  [sym_entity] = sym_entity,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [sym_tag_name] = sym_tag_name,
  [sym_class_name] = sym_class_name,
  [sym_annotation] = sym_annotation,
  [sym_webvtt] = sym_webvtt,
  [sym_header] = sym_header,
  [sym_metadata] = sym_metadata,
  [sym_metadata_value] = sym_metadata_value,
  [sym__block] = sym__block,
  [sym_style] = sym_style,
  [sym_region] = sym_region,
  [sym_cue] = sym_cue,
  [sym_cue_identifier] = sym_cue_identifier,
  [sym_cue_timing] = sym_cue_timing,
  [sym__settings] = sym__settings,
  [sym_setting] = sym_setting,
  [sym_setting_value] = sym_setting_value,
  [sym_cue_text] = sym_cue_text,
  [sym_start_tag] = sym_start_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_timestamp_tag] = sym_timestamp_tag,
  [aux_sym_webvtt_repeat1] = aux_sym_webvtt_repeat1,
  [aux_sym_header_repeat1] = aux_sym_header_repeat1,
  [aux_sym_region_repeat1] = aux_sym_region_repeat1,
  [aux_sym_cue_repeat1] = aux_sym_cue_repeat1,
  [aux_sym__settings_repeat1] = aux_sym__settings_repeat1,
  [aux_sym_setting_value_repeat1] = aux_sym_setting_value_repeat1,
  [aux_sym_cue_text_repeat1] = aux_sym_cue_text_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_webvtt_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BOM] = {
    .visible = true,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__blank] = {
    .visible = false,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_WEBVTT] = {
    .visible = true,
    .named = false,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_metadata_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_metadata_value_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_style_token1] = {
    .visible = true,
    .named = false,
  },
  [sym_stylesheet] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_region_token1] = {
    .visible = true,
    .named = false,
  },
  [sym__keyword_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_timestamp] = {
    .visible = true,
    .named = true,
  },
  [sym_setting_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_setting_part] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_cue_text_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_entity] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_class_name] = {
    .visible = true,
    .named = true,
  },
  [sym_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_webvtt] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata_value] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_style] = {
    .visible = true,
    .named = true,
  },
  [sym_region] = {
    .visible = true,
    .named = true,
  },
  [sym_cue] = {
    .visible = true,
    .named = true,
  },
  [sym_cue_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_cue_timing] = {
    .visible = true,
    .named = true,
  },
  [sym__settings] = {
    .visible = false,
    .named = true,
  },
  [sym_setting] = {
    .visible = true,
    .named = true,
  },
  [sym_setting_value] = {
    .visible = true,
    .named = true,
  },
  [sym_cue_text] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_timestamp_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_webvtt_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_region_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cue_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__settings_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_setting_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cue_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_annotation = 1,
  field_class = 2,
  field_end = 3,
  field_identifier = 4,
  field_name = 5,
  field_start = 6,
  field_timing = 7,
  field_title = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_annotation] = "annotation",
  [field_class] = "class",
  [field_end] = "end",
  [field_identifier] = "identifier",
  [field_name] = "name",
  [field_start] = "start",
  [field_timing] = "timing",
  [field_title] = "title",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 2},
  [10] = {.index = 15, .length = 1},
  [11] = {.index = 16, .length = 1},
  [12] = {.index = 17, .length = 2},
  [13] = {.index = 19, .length = 2},
  [14] = {.index = 21, .length = 2},
  [15] = {.index = 23, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_title, 2},
  [2] =
    {field_timing, 0},
  [3] =
    {field_name, 0},
    {field_value, 2},
  [5] =
    {field_identifier, 0},
    {field_timing, 2},
  [7] =
    {field_end, 2},
    {field_start, 0},
  [9] =
    {field_name, 0},
    {field_value, 3},
  [11] =
    {field_end, 3},
    {field_start, 0},
  [13] =
    {field_end, 4},
    {field_start, 0},
  [15] =
    {field_name, 1},
  [16] =
    {field_class, 1},
  [17] =
    {field_class, 2, .inherited = true},
    {field_name, 1},
  [19] =
    {field_class, 0, .inherited = true},
    {field_class, 1, .inherited = true},
  [21] =
    {field_annotation, 3},
    {field_name, 1},
  [23] =
    {field_annotation, 4},
    {field_class, 2, .inherited = true},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(52);
      ADVANCE_MAP(
        '\n', 53,
        '\r', 1,
        '&', 113,
        ',', 111,
        '.', 120,
        ':', 62,
        '<', 118,
        '=', 63,
        '>', 121,
        'R', 124,
        'S', 132,
        'W', 125,
        0xfeff, 54,
        '\t', 58,
        ' ', 58,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      if (lookahead != 0) ADVANCE(97);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(53);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 53,
        '\r', 1,
        '-', 11,
        '.', 120,
        '>', 121,
        'W', 23,
        0xfeff, 54,
        '\t', 58,
        ' ', 58,
      );
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(56);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(57);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(41);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(55);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(55);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead == '>') ADVANCE(121);
      if (lookahead != 0) ADVANCE(139);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(42);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == '.') ADVANCE(38);
      END_STATE();
    case 13:
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == ':') ADVANCE(36);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(36);
      END_STATE();
    case 18:
      if (lookahead == ';') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      if (lookahead == ';') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 20:
      if (lookahead == ';') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == '>') ADVANCE(108);
      END_STATE();
    case 22:
      if (lookahead == 'B') ADVANCE(26);
      END_STATE();
    case 23:
      if (lookahead == 'E') ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == 'T') ADVANCE(59);
      END_STATE();
    case 25:
      if (lookahead == 'T') ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == 'V') ADVANCE(25);
      END_STATE();
    case 27:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 28:
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '&' &&
          lookahead != '<') ADVANCE(116);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(109);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 39:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 40:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '&' &&
          lookahead != '.' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(138);
      END_STATE();
    case 41:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(99);
      END_STATE();
    case 42:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(103);
      END_STATE();
    case 43:
      if (eof) ADVANCE(52);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '&') ADVANCE(114);
      if (lookahead == '<') ADVANCE(119);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(116);
      END_STATE();
    case 44:
      if (eof) ADVANCE(52);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == ',') ADVANCE(111);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(112);
      END_STATE();
    case 45:
      if (eof) ADVANCE(52);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == ':') ADVANCE(62);
      if (lookahead == '=') ADVANCE(63);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 46:
      if (eof) ADVANCE(52);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == ':') ADVANCE(62);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(110);
      END_STATE();
    case 47:
      if (eof) ADVANCE(52);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0) ADVANCE(97);
      END_STATE();
    case 48:
      if (eof) ADVANCE(52);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead != 0) ADVANCE(97);
      END_STATE();
    case 49:
      if (eof) ADVANCE(52);
      if (lookahead == '\n') ADVANCE(56);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 50:
      if (eof) ADVANCE(52);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == 'N') ADVANCE(82);
      if (lookahead == 'R') ADVANCE(74);
      if (lookahead == 'S') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      if (lookahead != 0) ADVANCE(97);
      END_STATE();
    case 51:
      if (eof) ADVANCE(52);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead != 0) ADVANCE(103);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_webvtt_token1);
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '\r') ADVANCE(1);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_BOM);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(4);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__blank);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(4);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_WEBVTT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_WEBVTT);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_title);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_metadata_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ':' &&
          lookahead != '=') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == '.') ADVANCE(95);
      if (lookahead == ':') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == '.') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == ':') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == ':') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == ':') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == ':') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == ';') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == ';') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == ';') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'E') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'E') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'E') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'G') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'I') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'L') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'N') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'O') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'O') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'T') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'T') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'Y') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(109);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_metadata_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\r') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0) ADVANCE(107);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\r') ADVANCE(7);
      if (lookahead != 0) ADVANCE(99);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_style_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_style_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(100);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_style_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(107);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_stylesheet);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead == '\r') ADVANCE(10);
      if (lookahead != 0) ADVANCE(103);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_region_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_region_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(104);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_region_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(107);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym__keyword_identifier);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_timestamp);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_setting_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(110);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_setting_part);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ',') ADVANCE(112);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '#') ADVANCE(86);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '#') ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(aux_sym_cue_text_token1);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '&' &&
          lookahead != '<') ADVANCE(116);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_entity);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(122);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(122);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < '/' || '9' < lookahead) &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          (lookahead < 'a' || 'z' < lookahead)) ADVANCE(115);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'B') ADVANCE(135);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'E') ADVANCE(127);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'E') ADVANCE(123);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'E') ADVANCE(101);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'G') ADVANCE(128);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'I') ADVANCE(131);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'L') ADVANCE(126);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'N') ADVANCE(105);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'O') ADVANCE(130);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'T') ADVANCE(136);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'T') ADVANCE(60);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'T') ADVANCE(133);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'V') ADVANCE(134);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'Y') ADVANCE(129);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(137);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_class_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '&' &&
          lookahead != '.' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(138);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_annotation);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '>') ADVANCE(139);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 43},
  [3] = {.lex_state = 43},
  [4] = {.lex_state = 50},
  [5] = {.lex_state = 43},
  [6] = {.lex_state = 43},
  [7] = {.lex_state = 43},
  [8] = {.lex_state = 43},
  [9] = {.lex_state = 43},
  [10] = {.lex_state = 43},
  [11] = {.lex_state = 43},
  [12] = {.lex_state = 43},
  [13] = {.lex_state = 43},
  [14] = {.lex_state = 46},
  [15] = {.lex_state = 47},
  [16] = {.lex_state = 44},
  [17] = {.lex_state = 46},
  [18] = {.lex_state = 44},
  [19] = {.lex_state = 46},
  [20] = {.lex_state = 44},
  [21] = {.lex_state = 46},
  [22] = {.lex_state = 44},
  [23] = {.lex_state = 44},
  [24] = {.lex_state = 43},
  [25] = {.lex_state = 44},
  [26] = {.lex_state = 48},
  [27] = {.lex_state = 46},
  [28] = {.lex_state = 43},
  [29] = {.lex_state = 43},
  [30] = {.lex_state = 45},
  [31] = {.lex_state = 49},
  [32] = {.lex_state = 46},
  [33] = {.lex_state = 43},
  [34] = {.lex_state = 45},
  [35] = {.lex_state = 46},
  [36] = {.lex_state = 43},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 43},
  [39] = {.lex_state = 43},
  [40] = {.lex_state = 43},
  [41] = {.lex_state = 43},
  [42] = {.lex_state = 43},
  [43] = {.lex_state = 43},
  [44] = {.lex_state = 43},
  [45] = {.lex_state = 43},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 43},
  [48] = {.lex_state = 43},
  [49] = {.lex_state = 43},
  [50] = {.lex_state = 43},
  [51] = {.lex_state = 43},
  [52] = {.lex_state = 43},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 43},
  [55] = {.lex_state = 43},
  [56] = {.lex_state = 43},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 43},
  [59] = {.lex_state = 43},
  [60] = {.lex_state = 43},
  [61] = {.lex_state = 51},
  [62] = {.lex_state = 43},
  [63] = {.lex_state = 43},
  [64] = {.lex_state = 43},
  [65] = {.lex_state = 43},
  [66] = {.lex_state = 43},
  [67] = {.lex_state = 43},
  [68] = {.lex_state = 43},
  [69] = {.lex_state = 43},
  [70] = {.lex_state = 43},
  [71] = {.lex_state = 43},
  [72] = {.lex_state = 43},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 43},
  [75] = {.lex_state = 43},
  [76] = {.lex_state = 43},
  [77] = {.lex_state = 43},
  [78] = {.lex_state = 43},
  [79] = {.lex_state = 46},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 9},
  [82] = {.lex_state = 30},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 43},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 43},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 9},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 43},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 40},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 30},
  [96] = {.lex_state = 9},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 9},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 2},
  [103] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_webvtt_token1] = ACTIONS(1),
    [anon_sym_BOM] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__blank] = ACTIONS(1),
    [sym__ws] = ACTIONS(1),
    [anon_sym_WEBVTT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_metadata_value_token1] = ACTIONS(1),
    [aux_sym_style_token1] = ACTIONS(1),
    [aux_sym_region_token1] = ACTIONS(1),
    [sym_timestamp] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [sym_entity] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_webvtt] = STATE(98),
    [sym_header] = STATE(59),
    [aux_sym_webvtt_token1] = ACTIONS(3),
    [anon_sym_BOM] = ACTIONS(5),
    [anon_sym_WEBVTT] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(11), 1,
      sym__newline,
    ACTIONS(15), 1,
      anon_sym_AMP,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    STATE(74), 1,
      sym_cue_text,
    ACTIONS(9), 2,
      ts_builtin_sym_end,
      sym__blank,
    ACTIONS(13), 4,
      sym__ws,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
    STATE(3), 4,
      sym_start_tag,
      sym_end_tag,
      sym_timestamp_tag,
      aux_sym_cue_text_repeat1,
  [32] = 7,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    ACTIONS(23), 1,
      sym__newline,
    ACTIONS(27), 1,
      anon_sym_AMP,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      sym__blank,
    ACTIONS(25), 4,
      sym__ws,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
    STATE(5), 4,
      sym_start_tag,
      sym_end_tag,
      sym_timestamp_tag,
      aux_sym_cue_text_repeat1,
  [61] = 10,
    ACTIONS(31), 1,
      aux_sym_metadata_value_token1,
    ACTIONS(33), 1,
      sym_comment,
    ACTIONS(35), 1,
      aux_sym_style_token1,
    ACTIONS(37), 1,
      aux_sym_region_token1,
    ACTIONS(39), 1,
      sym__keyword_identifier,
    ACTIONS(41), 1,
      sym_timestamp,
    STATE(48), 1,
      sym_cue_timing,
    STATE(96), 1,
      sym_cue_identifier,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      sym__blank,
    STATE(84), 4,
      sym__block,
      sym_style,
      sym_region,
      sym_cue,
  [96] = 7,
    ACTIONS(45), 1,
      sym__newline,
    ACTIONS(50), 1,
      anon_sym_AMP,
    ACTIONS(53), 1,
      anon_sym_LT,
    ACTIONS(56), 1,
      anon_sym_LT_SLASH,
    ACTIONS(43), 2,
      ts_builtin_sym_end,
      sym__blank,
    ACTIONS(47), 4,
      sym__ws,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
    STATE(5), 4,
      sym_start_tag,
      sym_end_tag,
      sym_timestamp_tag,
      aux_sym_cue_text_repeat1,
  [125] = 2,
    ACTIONS(61), 3,
      sym__newline,
      anon_sym_AMP,
      anon_sym_LT,
    ACTIONS(59), 7,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
      anon_sym_LT_SLASH,
  [140] = 2,
    ACTIONS(65), 3,
      sym__newline,
      anon_sym_AMP,
      anon_sym_LT,
    ACTIONS(63), 7,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
      anon_sym_LT_SLASH,
  [155] = 2,
    ACTIONS(69), 3,
      sym__newline,
      anon_sym_AMP,
      anon_sym_LT,
    ACTIONS(67), 7,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
      anon_sym_LT_SLASH,
  [170] = 2,
    ACTIONS(73), 3,
      sym__newline,
      anon_sym_AMP,
      anon_sym_LT,
    ACTIONS(71), 7,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
      anon_sym_LT_SLASH,
  [185] = 2,
    ACTIONS(77), 3,
      sym__newline,
      anon_sym_AMP,
      anon_sym_LT,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
      anon_sym_LT_SLASH,
  [200] = 2,
    ACTIONS(81), 3,
      sym__newline,
      anon_sym_AMP,
      anon_sym_LT,
    ACTIONS(79), 7,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
      anon_sym_LT_SLASH,
  [215] = 2,
    ACTIONS(85), 3,
      sym__newline,
      anon_sym_AMP,
      anon_sym_LT,
    ACTIONS(83), 7,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
      anon_sym_LT_SLASH,
  [230] = 2,
    ACTIONS(89), 3,
      sym__newline,
      anon_sym_AMP,
      anon_sym_LT,
    ACTIONS(87), 7,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
      aux_sym_cue_text_token1,
      sym_text,
      sym_entity,
      anon_sym_LT_SLASH,
  [245] = 5,
    ACTIONS(93), 1,
      sym__newline,
    ACTIONS(95), 1,
      sym_setting_name,
    STATE(28), 1,
      sym_setting,
    STATE(71), 1,
      sym__settings,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      sym__blank,
  [262] = 5,
    ACTIONS(99), 1,
      sym__newline,
    ACTIONS(101), 1,
      sym__ws,
    ACTIONS(103), 1,
      aux_sym_metadata_value_token1,
    STATE(72), 1,
      sym_metadata_value,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym__blank,
  [279] = 4,
    ACTIONS(107), 1,
      sym__newline,
    ACTIONS(109), 1,
      sym_setting_part,
    STATE(49), 1,
      sym_setting_value,
    ACTIONS(105), 3,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
  [294] = 5,
    ACTIONS(95), 1,
      sym_setting_name,
    ACTIONS(113), 1,
      sym__newline,
    STATE(28), 1,
      sym_setting,
    STATE(62), 1,
      sym__settings,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      sym__blank,
  [311] = 4,
    ACTIONS(117), 1,
      sym__newline,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    STATE(22), 1,
      aux_sym_setting_value_repeat1,
    ACTIONS(115), 3,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
  [326] = 5,
    ACTIONS(95), 1,
      sym_setting_name,
    ACTIONS(123), 1,
      sym__newline,
    STATE(28), 1,
      sym_setting,
    STATE(70), 1,
      sym__settings,
    ACTIONS(121), 2,
      ts_builtin_sym_end,
      sym__blank,
  [343] = 3,
    ACTIONS(127), 1,
      sym__newline,
    ACTIONS(129), 1,
      sym_setting_part,
    ACTIONS(125), 4,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
      anon_sym_COMMA,
  [356] = 5,
    ACTIONS(95), 1,
      sym_setting_name,
    ACTIONS(133), 1,
      sym__newline,
    STATE(28), 1,
      sym_setting,
    STATE(76), 1,
      sym__settings,
    ACTIONS(131), 2,
      ts_builtin_sym_end,
      sym__blank,
  [373] = 4,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    ACTIONS(137), 1,
      sym__newline,
    STATE(23), 1,
      aux_sym_setting_value_repeat1,
    ACTIONS(135), 3,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
  [388] = 4,
    ACTIONS(141), 1,
      sym__newline,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    STATE(23), 1,
      aux_sym_setting_value_repeat1,
    ACTIONS(139), 3,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
  [403] = 4,
    ACTIONS(148), 1,
      sym__newline,
    ACTIONS(150), 1,
      sym__ws,
    STATE(36), 1,
      aux_sym_header_repeat1,
    ACTIONS(146), 2,
      ts_builtin_sym_end,
      sym__blank,
  [417] = 2,
    ACTIONS(141), 1,
      sym__newline,
    ACTIONS(139), 4,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
      anon_sym_COMMA,
  [427] = 4,
    ACTIONS(154), 1,
      sym__newline,
    ACTIONS(156), 1,
      aux_sym_metadata_value_token1,
    STATE(65), 1,
      sym_metadata_value,
    ACTIONS(152), 2,
      ts_builtin_sym_end,
      sym__blank,
  [441] = 3,
    ACTIONS(160), 1,
      sym__newline,
    ACTIONS(162), 1,
      anon_sym_COLON,
    ACTIONS(158), 3,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
  [453] = 4,
    ACTIONS(166), 1,
      sym__newline,
    ACTIONS(168), 1,
      sym__ws,
    STATE(29), 1,
      aux_sym__settings_repeat1,
    ACTIONS(164), 2,
      ts_builtin_sym_end,
      sym__blank,
  [467] = 4,
    ACTIONS(172), 1,
      sym__newline,
    ACTIONS(174), 1,
      sym__ws,
    STATE(33), 1,
      aux_sym__settings_repeat1,
    ACTIONS(170), 2,
      ts_builtin_sym_end,
      sym__blank,
  [481] = 4,
    ACTIONS(178), 1,
      sym__newline,
    ACTIONS(180), 1,
      sym_metadata_name,
    STATE(68), 1,
      sym_metadata,
    ACTIONS(176), 2,
      ts_builtin_sym_end,
      sym__blank,
  [495] = 4,
    ACTIONS(148), 1,
      sym__newline,
    ACTIONS(184), 1,
      sym_title,
    STATE(55), 1,
      aux_sym_header_repeat1,
    ACTIONS(182), 2,
      ts_builtin_sym_end,
      sym__blank,
  [509] = 4,
    ACTIONS(95), 1,
      sym_setting_name,
    ACTIONS(188), 1,
      sym__newline,
    STATE(50), 1,
      sym_setting,
    ACTIONS(186), 2,
      ts_builtin_sym_end,
      sym__blank,
  [523] = 4,
    ACTIONS(192), 1,
      sym__newline,
    ACTIONS(194), 1,
      sym__ws,
    STATE(33), 1,
      aux_sym__settings_repeat1,
    ACTIONS(190), 2,
      ts_builtin_sym_end,
      sym__blank,
  [537] = 3,
    ACTIONS(199), 1,
      sym__newline,
    ACTIONS(197), 2,
      ts_builtin_sym_end,
      sym__blank,
    ACTIONS(201), 2,
      anon_sym_COLON,
      anon_sym_EQ,
  [549] = 4,
    ACTIONS(95), 1,
      sym_setting_name,
    ACTIONS(172), 1,
      sym__newline,
    STATE(50), 1,
      sym_setting,
    ACTIONS(170), 2,
      ts_builtin_sym_end,
      sym__blank,
  [563] = 3,
    ACTIONS(148), 1,
      sym__newline,
    STATE(56), 1,
      aux_sym_header_repeat1,
    ACTIONS(182), 2,
      ts_builtin_sym_end,
      sym__blank,
  [574] = 3,
    ACTIONS(205), 1,
      anon_sym_DOT,
    STATE(37), 1,
      aux_sym_start_tag_repeat1,
    ACTIONS(203), 2,
      sym__ws,
      anon_sym_GT,
  [585] = 3,
    ACTIONS(210), 1,
      sym__newline,
    STATE(38), 1,
      aux_sym_region_repeat1,
    ACTIONS(208), 2,
      ts_builtin_sym_end,
      sym__blank,
  [596] = 3,
    ACTIONS(215), 1,
      sym__newline,
    STATE(44), 1,
      aux_sym_cue_repeat1,
    ACTIONS(213), 2,
      ts_builtin_sym_end,
      sym__blank,
  [607] = 3,
    ACTIONS(219), 1,
      sym__newline,
    ACTIONS(221), 1,
      sym__ws,
    ACTIONS(217), 2,
      ts_builtin_sym_end,
      sym__blank,
  [618] = 3,
    ACTIONS(225), 1,
      sym__newline,
    STATE(41), 1,
      aux_sym_cue_repeat1,
    ACTIONS(223), 2,
      ts_builtin_sym_end,
      sym__blank,
  [629] = 3,
    ACTIONS(230), 1,
      sym__newline,
    STATE(47), 1,
      aux_sym_region_repeat1,
    ACTIONS(228), 2,
      ts_builtin_sym_end,
      sym__blank,
  [640] = 3,
    ACTIONS(148), 1,
      sym__newline,
    STATE(56), 1,
      aux_sym_header_repeat1,
    ACTIONS(232), 2,
      ts_builtin_sym_end,
      sym__blank,
  [651] = 3,
    ACTIONS(215), 1,
      sym__newline,
    STATE(41), 1,
      aux_sym_cue_repeat1,
    ACTIONS(234), 2,
      ts_builtin_sym_end,
      sym__blank,
  [662] = 3,
    ACTIONS(238), 1,
      sym__newline,
    ACTIONS(240), 1,
      sym__ws,
    ACTIONS(236), 2,
      ts_builtin_sym_end,
      sym__blank,
  [673] = 4,
    ACTIONS(242), 1,
      sym__ws,
    ACTIONS(244), 1,
      anon_sym_DOT,
    ACTIONS(246), 1,
      anon_sym_GT,
    STATE(53), 1,
      aux_sym_start_tag_repeat1,
  [686] = 3,
    ACTIONS(230), 1,
      sym__newline,
    STATE(38), 1,
      aux_sym_region_repeat1,
    ACTIONS(248), 2,
      ts_builtin_sym_end,
      sym__blank,
  [697] = 3,
    ACTIONS(215), 1,
      sym__newline,
    STATE(51), 1,
      aux_sym_cue_repeat1,
    ACTIONS(250), 2,
      ts_builtin_sym_end,
      sym__blank,
  [708] = 2,
    ACTIONS(254), 1,
      sym__newline,
    ACTIONS(252), 3,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
  [717] = 2,
    ACTIONS(192), 1,
      sym__newline,
    ACTIONS(190), 3,
      ts_builtin_sym_end,
      sym__blank,
      sym__ws,
  [726] = 3,
    ACTIONS(215), 1,
      sym__newline,
    STATE(41), 1,
      aux_sym_cue_repeat1,
    ACTIONS(256), 2,
      ts_builtin_sym_end,
      sym__blank,
  [737] = 3,
    ACTIONS(260), 1,
      sym__newline,
    ACTIONS(262), 1,
      sym__ws,
    ACTIONS(258), 2,
      ts_builtin_sym_end,
      sym__blank,
  [748] = 4,
    ACTIONS(244), 1,
      anon_sym_DOT,
    ACTIONS(264), 1,
      sym__ws,
    ACTIONS(266), 1,
      anon_sym_GT,
    STATE(37), 1,
      aux_sym_start_tag_repeat1,
  [761] = 3,
    ACTIONS(148), 1,
      sym__newline,
    STATE(43), 1,
      aux_sym_header_repeat1,
    ACTIONS(268), 2,
      ts_builtin_sym_end,
      sym__blank,
  [772] = 3,
    ACTIONS(148), 1,
      sym__newline,
    STATE(56), 1,
      aux_sym_header_repeat1,
    ACTIONS(270), 2,
      ts_builtin_sym_end,
      sym__blank,
  [783] = 3,
    ACTIONS(274), 1,
      sym__newline,
    STATE(56), 1,
      aux_sym_header_repeat1,
    ACTIONS(272), 2,
      ts_builtin_sym_end,
      sym__blank,
  [794] = 1,
    ACTIONS(277), 3,
      sym__ws,
      anon_sym_DOT,
      anon_sym_GT,
  [800] = 2,
    ACTIONS(281), 1,
      sym__newline,
    ACTIONS(279), 2,
      ts_builtin_sym_end,
      sym__blank,
  [808] = 3,
    ACTIONS(283), 1,
      ts_builtin_sym_end,
    ACTIONS(285), 1,
      sym__blank,
    STATE(63), 1,
      aux_sym_webvtt_repeat1,
  [818] = 3,
    ACTIONS(285), 1,
      sym__blank,
    ACTIONS(287), 1,
      ts_builtin_sym_end,
    STATE(67), 1,
      aux_sym_webvtt_repeat1,
  [828] = 2,
    ACTIONS(291), 1,
      sym_stylesheet,
    ACTIONS(289), 2,
      ts_builtin_sym_end,
      sym__blank,
  [836] = 2,
    ACTIONS(295), 1,
      sym__newline,
    ACTIONS(293), 2,
      ts_builtin_sym_end,
      sym__blank,
  [844] = 3,
    ACTIONS(285), 1,
      sym__blank,
    ACTIONS(297), 1,
      ts_builtin_sym_end,
    STATE(67), 1,
      aux_sym_webvtt_repeat1,
  [854] = 3,
    ACTIONS(285), 1,
      sym__blank,
    ACTIONS(299), 1,
      ts_builtin_sym_end,
    STATE(60), 1,
      aux_sym_webvtt_repeat1,
  [864] = 2,
    ACTIONS(303), 1,
      sym__newline,
    ACTIONS(301), 2,
      ts_builtin_sym_end,
      sym__blank,
  [872] = 3,
    ACTIONS(285), 1,
      sym__blank,
    ACTIONS(299), 1,
      ts_builtin_sym_end,
    STATE(67), 1,
      aux_sym_webvtt_repeat1,
  [882] = 3,
    ACTIONS(305), 1,
      ts_builtin_sym_end,
    ACTIONS(307), 1,
      sym__blank,
    STATE(67), 1,
      aux_sym_webvtt_repeat1,
  [892] = 2,
    ACTIONS(310), 1,
      sym__newline,
    ACTIONS(272), 2,
      ts_builtin_sym_end,
      sym__blank,
  [900] = 3,
    ACTIONS(285), 1,
      sym__blank,
    ACTIONS(297), 1,
      ts_builtin_sym_end,
    STATE(66), 1,
      aux_sym_webvtt_repeat1,
  [910] = 2,
    ACTIONS(314), 1,
      sym__newline,
    ACTIONS(312), 2,
      ts_builtin_sym_end,
      sym__blank,
  [918] = 2,
    ACTIONS(316), 1,
      sym__newline,
    ACTIONS(208), 2,
      ts_builtin_sym_end,
      sym__blank,
  [926] = 2,
    ACTIONS(320), 1,
      sym__newline,
    ACTIONS(318), 2,
      ts_builtin_sym_end,
      sym__blank,
  [934] = 3,
    ACTIONS(7), 1,
      anon_sym_WEBVTT,
    ACTIONS(322), 1,
      anon_sym_BOM,
    STATE(69), 1,
      sym_header,
  [944] = 2,
    ACTIONS(324), 1,
      sym__newline,
    ACTIONS(223), 2,
      ts_builtin_sym_end,
      sym__blank,
  [952] = 2,
    ACTIONS(328), 1,
      sym__newline,
    ACTIONS(326), 2,
      ts_builtin_sym_end,
      sym__blank,
  [960] = 2,
    ACTIONS(332), 1,
      sym__newline,
    ACTIONS(330), 2,
      ts_builtin_sym_end,
      sym__blank,
  [968] = 2,
    ACTIONS(336), 1,
      sym__newline,
    ACTIONS(334), 2,
      ts_builtin_sym_end,
      sym__blank,
  [976] = 2,
    ACTIONS(340), 1,
      sym__newline,
    ACTIONS(338), 2,
      ts_builtin_sym_end,
      sym__blank,
  [984] = 2,
    ACTIONS(95), 1,
      sym_setting_name,
    STATE(50), 1,
      sym_setting,
  [991] = 2,
    ACTIONS(342), 1,
      sym__ws,
    ACTIONS(344), 1,
      anon_sym_DASH_DASH_GT,
  [998] = 2,
    ACTIONS(346), 1,
      anon_sym_GT,
    ACTIONS(348), 1,
      sym_annotation,
  [1005] = 2,
    ACTIONS(350), 1,
      sym_timestamp,
    ACTIONS(352), 1,
      sym_tag_name,
  [1012] = 2,
    ACTIONS(354), 1,
      sym__ws,
    ACTIONS(356), 1,
      sym_timestamp,
  [1019] = 1,
    ACTIONS(305), 2,
      ts_builtin_sym_end,
      sym__blank,
  [1024] = 2,
    ACTIONS(7), 1,
      anon_sym_WEBVTT,
    STATE(64), 1,
      sym_header,
  [1031] = 1,
    ACTIONS(358), 2,
      ts_builtin_sym_end,
      sym__blank,
  [1036] = 2,
    ACTIONS(7), 1,
      anon_sym_WEBVTT,
    STATE(69), 1,
      sym_header,
  [1043] = 2,
    ACTIONS(360), 1,
      anon_sym_GT,
    ACTIONS(362), 1,
      sym_annotation,
  [1050] = 2,
    ACTIONS(41), 1,
      sym_timestamp,
    STATE(39), 1,
      sym_cue_timing,
  [1057] = 1,
    ACTIONS(364), 2,
      ts_builtin_sym_end,
      sym__blank,
  [1062] = 2,
    ACTIONS(366), 1,
      sym__ws,
    ACTIONS(368), 1,
      sym_timestamp,
  [1069] = 1,
    ACTIONS(370), 1,
      sym_timestamp,
  [1073] = 1,
    ACTIONS(372), 1,
      sym_class_name,
  [1077] = 1,
    ACTIONS(374), 1,
      anon_sym_GT,
  [1081] = 1,
    ACTIONS(376), 1,
      sym_tag_name,
  [1085] = 1,
    ACTIONS(378), 1,
      sym__newline,
  [1089] = 1,
    ACTIONS(380), 1,
      anon_sym_GT,
  [1093] = 1,
    ACTIONS(382), 1,
      ts_builtin_sym_end,
  [1097] = 1,
    ACTIONS(384), 1,
      sym__newline,
  [1101] = 1,
    ACTIONS(386), 1,
      anon_sym_DASH_DASH_GT,
  [1105] = 1,
    ACTIONS(388), 1,
      anon_sym_GT,
  [1109] = 1,
    ACTIONS(390), 1,
      anon_sym_GT,
  [1113] = 1,
    ACTIONS(368), 1,
      sym_timestamp,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 61,
  [SMALL_STATE(5)] = 96,
  [SMALL_STATE(6)] = 125,
  [SMALL_STATE(7)] = 140,
  [SMALL_STATE(8)] = 155,
  [SMALL_STATE(9)] = 170,
  [SMALL_STATE(10)] = 185,
  [SMALL_STATE(11)] = 200,
  [SMALL_STATE(12)] = 215,
  [SMALL_STATE(13)] = 230,
  [SMALL_STATE(14)] = 245,
  [SMALL_STATE(15)] = 262,
  [SMALL_STATE(16)] = 279,
  [SMALL_STATE(17)] = 294,
  [SMALL_STATE(18)] = 311,
  [SMALL_STATE(19)] = 326,
  [SMALL_STATE(20)] = 343,
  [SMALL_STATE(21)] = 356,
  [SMALL_STATE(22)] = 373,
  [SMALL_STATE(23)] = 388,
  [SMALL_STATE(24)] = 403,
  [SMALL_STATE(25)] = 417,
  [SMALL_STATE(26)] = 427,
  [SMALL_STATE(27)] = 441,
  [SMALL_STATE(28)] = 453,
  [SMALL_STATE(29)] = 467,
  [SMALL_STATE(30)] = 481,
  [SMALL_STATE(31)] = 495,
  [SMALL_STATE(32)] = 509,
  [SMALL_STATE(33)] = 523,
  [SMALL_STATE(34)] = 537,
  [SMALL_STATE(35)] = 549,
  [SMALL_STATE(36)] = 563,
  [SMALL_STATE(37)] = 574,
  [SMALL_STATE(38)] = 585,
  [SMALL_STATE(39)] = 596,
  [SMALL_STATE(40)] = 607,
  [SMALL_STATE(41)] = 618,
  [SMALL_STATE(42)] = 629,
  [SMALL_STATE(43)] = 640,
  [SMALL_STATE(44)] = 651,
  [SMALL_STATE(45)] = 662,
  [SMALL_STATE(46)] = 673,
  [SMALL_STATE(47)] = 686,
  [SMALL_STATE(48)] = 697,
  [SMALL_STATE(49)] = 708,
  [SMALL_STATE(50)] = 717,
  [SMALL_STATE(51)] = 726,
  [SMALL_STATE(52)] = 737,
  [SMALL_STATE(53)] = 748,
  [SMALL_STATE(54)] = 761,
  [SMALL_STATE(55)] = 772,
  [SMALL_STATE(56)] = 783,
  [SMALL_STATE(57)] = 794,
  [SMALL_STATE(58)] = 800,
  [SMALL_STATE(59)] = 808,
  [SMALL_STATE(60)] = 818,
  [SMALL_STATE(61)] = 828,
  [SMALL_STATE(62)] = 836,
  [SMALL_STATE(63)] = 844,
  [SMALL_STATE(64)] = 854,
  [SMALL_STATE(65)] = 864,
  [SMALL_STATE(66)] = 872,
  [SMALL_STATE(67)] = 882,
  [SMALL_STATE(68)] = 892,
  [SMALL_STATE(69)] = 900,
  [SMALL_STATE(70)] = 910,
  [SMALL_STATE(71)] = 918,
  [SMALL_STATE(72)] = 926,
  [SMALL_STATE(73)] = 934,
  [SMALL_STATE(74)] = 944,
  [SMALL_STATE(75)] = 952,
  [SMALL_STATE(76)] = 960,
  [SMALL_STATE(77)] = 968,
  [SMALL_STATE(78)] = 976,
  [SMALL_STATE(79)] = 984,
  [SMALL_STATE(80)] = 991,
  [SMALL_STATE(81)] = 998,
  [SMALL_STATE(82)] = 1005,
  [SMALL_STATE(83)] = 1012,
  [SMALL_STATE(84)] = 1019,
  [SMALL_STATE(85)] = 1024,
  [SMALL_STATE(86)] = 1031,
  [SMALL_STATE(87)] = 1036,
  [SMALL_STATE(88)] = 1043,
  [SMALL_STATE(89)] = 1050,
  [SMALL_STATE(90)] = 1057,
  [SMALL_STATE(91)] = 1062,
  [SMALL_STATE(92)] = 1069,
  [SMALL_STATE(93)] = 1073,
  [SMALL_STATE(94)] = 1077,
  [SMALL_STATE(95)] = 1081,
  [SMALL_STATE(96)] = 1085,
  [SMALL_STATE(97)] = 1089,
  [SMALL_STATE(98)] = 1093,
  [SMALL_STATE(99)] = 1097,
  [SMALL_STATE(100)] = 1101,
  [SMALL_STATE(101)] = 1105,
  [SMALL_STATE(102)] = 1109,
  [SMALL_STATE(103)] = 1113,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_cue_repeat1, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cue_repeat1, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_text, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_text, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_webvtt_repeat1, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_cue_text_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cue_text_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cue_text_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cue_text_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cue_text_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cue_text_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_timestamp_tag, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_timestamp_tag, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 10),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 10),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 10),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 10),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 12),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 12),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 10),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 10),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 5, 0, 14),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 5, 0, 14),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 5, 0, 12),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 5, 0, 12),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 6, 0, 15),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 6, 0, 15),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_region_repeat1, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_region_repeat1, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 2, 0, 1),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata, 2, 0, 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 2, 0, 1),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_setting, 2, 0, 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 4, 0, 6),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 4, 0, 6),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting_value, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_setting_value, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 5, 0, 8),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 5, 0, 8),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_setting_value_repeat1, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_setting_value_repeat1, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 6, 0, 9),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 6, 0, 9),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting_value, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_setting_value, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_setting_value_repeat1, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_setting_value_repeat1, 2, 0, 0),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_setting_value_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 3, 0, 1),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata, 3, 0, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 1, 0, 1),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_setting, 1, 0, 1),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__settings, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__settings, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__settings, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__settings, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_repeat1, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__settings, 3, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__settings, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__settings_repeat1, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__settings_repeat1, 2, 0, 0),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__settings_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 1, 0, 1),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata, 1, 0, 1),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 13),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 13), SHIFT_REPEAT(93),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_region_repeat1, 2, 0, 0),
  [210] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_region_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue, 3, 0, 5),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 3, 0, 6),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 3, 0, 6),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_cue_repeat1, 2, 0, 0),
  [225] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cue_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region, 1, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 4, 0, 2),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue, 4, 0, 5),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 4, 0, 8),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 4, 0, 8),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_region, 2, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue, 1, 0, 3),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 3, 0, 4),
  [254] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_setting, 3, 0, 4),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue, 2, 0, 3),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 5, 0, 9),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 5, 0, 9),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 2),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0),
  [274] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 11),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style, 3, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_webvtt, 1, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_webvtt, 4, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style, 2, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 5, 0, 6),
  [295] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 5, 0, 6),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_webvtt, 2, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_webvtt, 3, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 4, 0, 7),
  [303] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata, 4, 0, 7),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_webvtt_repeat1, 2, 0, 0),
  [307] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_webvtt_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [310] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 6, 0, 8),
  [314] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 6, 0, 8),
  [316] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_region_repeat1, 2, 0, 0),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 3, 0, 4),
  [320] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata, 3, 0, 4),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [324] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cue_repeat1, 2, 0, 0),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata_value, 1, 0, 0),
  [328] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata_value, 1, 0, 0),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_timing, 7, 0, 9),
  [332] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cue_timing, 7, 0, 9),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block, 1, 0, 0),
  [336] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [338] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style, 1, 0, 0),
  [340] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [358] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block, 2, 0, 0),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [364] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style, 4, 0, 0),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [382] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [384] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cue_identifier, 1, 0, 0),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_webvtt(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "webvtt",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
